### ISSUE TITLE
Error when the exercise hides the output

### ISSUE THREAD

**Issue by linsyking** [BoYanZh/JOJ-Submitter#4]
When an exercise hides the result, we expect to see the result. Currently it has some errors.

**Comment by BoYanZh** [comment]
It works for me correctly.

```bash
$ joj-submit https://joj.sjtu.edu.cn/d/ve280_fall_2022_weikang/homework/633c31a1dec511000656b32a/633ab1dadec511000656aaf4 test.zip cc -d
test.zip upload succeed, record url https://joj.sjtu.edu.cn/d/ve280_fall_2022_weikang/records/6345438db6a0b300081b56ee
status: Wrong Answer, accept number: 20, score: 200, total time: 205 ms, peak memory: 8.398 MiB
details:
#0: Wrong Answer, time: 2 ms, memory: 388.0 KiB
Stderr:

Your Answer:

JOJ Answer:

#15: Wrong Answer, time: 1 ms, memory: 332.0 KiB
Stderr:

Your Answer:

JOJ Answer:

```

**Comment by linsyking** [comment]
I got this:
```
[Extension Host] error Traceback (most recent call last):
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\Scripts\joj-submit-script.py", line 11, in <module>
    load_entry_point('joj-submitter==0.0.8', 'console_scripts', 'joj-submit')()
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\joj_submitter\__init__.py", line 9, in main
    app()
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\typer\main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\joj_submitter\__main__.py", line 311, in main
    accepted = worker.submit(
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\joj_submitter\__main__.py", line 178, in submit
    res = self.get_status(response.url)
  File "C:\Users\King\AppData\Local\Programs\Python\Python38\lib\site-packages\joj_submitter\__main__.py", line 122, in get_status
    detail_url = "https://joj.sjtu.edu.cn" + status_soup.find("a").get("href")
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by BoYanZh** [comment]
Full command needed.

**Comment by linsyking** [comment]
```
joj-submit.exe "https://joj.sjtu.edu.cn/d/ve280_fall_2022_weikang/homework/633661dedec5110006568d38/633406f5dec51100065677f1" .\h3.zip cc [MY SID]
```

**Comment by BoYanZh** [comment]
Can not reproduce the error either. Please provide the HTML content of your record page. e.g. https://paste.ubuntu.com/p/KKZyjWVfVC/

**Comment by linsyking** [comment]
https://pastebin.mozilla.org/dCdDor11

**Comment by linsyking** [comment]
https://pastebin.mozilla.org/fakmREfP

**Comment by BoYanZh** [comment]
Fixed.

**Comment by linsyking** [comment]
Still got error.

**Comment by linsyking** [comment]
```
Traceback (most recent call last):
  File "/home/linsy/.local/bin/joj-submit", line 8, in <module>

sys.exit(main())
  File "/home/linsy/.local/lib/python3.10/site-packages/joj_submitter/__init__.py", line 9, in main
    app()
  File "/home/linsy/.local/lib/python3.10/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/linsy/.local/lib/python3.10/site-packages/click/core.py", line 829, in __call__

return self.main(*args, **kwargs)
  File "/home/linsy/.local/lib/python3.10/site-packages/click/core.py", line 782, in main

rv = self.invoke(ctx)
  File "/home/linsy/.local/lib/python3.10/site-packages/click/core.py", line 1066, in invoke

return ctx.invoke(self.callback, **ctx.params)
  File "/home/linsy/.local/lib/python3.10/site-packages/click/core.py", line 610, in invoke

return callback(*args, **kwargs)
  File "/home/linsy/.local/lib/python3.10/site-packages/typer/main.py", line 497, in wrapper

return callback(**use_params)  # type: ignore
  File "/home/linsy/.local/lib/python3.10/site-packages/joj_submitter/__main__.py", line 322, in main

 accepted = worker.submit(
  File "/home/linsy/.local/lib/python3.10/site-packages/joj_submitter/__main__.py", line 189, in submit

res = self.get_status(response.url)
  File "/home/linsy/.local/lib/python3.10/site-packages/joj_submitter/__main__.py", line 152, in get_status

extra_info=extra_info,
UnboundLocalError: local variable 'extra_info' referenced before assignment
```

**Comment by BoYanZh** [comment]
Fixed.
